name: Unzip Project

on:
  push:
    paths:
      - 'electricity-hub.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip project
        run: |
          mkdir temp
          unzip electricity-hub.zip -d temp
          rsync -av temp/ . --exclude electricity-hub.zip
          rm -rf temp

      - name: Commit unzipped files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzipped project"
          git push
